name: untitled1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  json_theme: ^7.0.0+3
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  dartz: ^0.10.1
  youtube_player_flutter: ^9.1.1
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  awesome_dialog: ^3.2.1
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
     -  assets/light theme.json
     -  assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
